---
# Podman/httpd-tools는 1Play에서 설치했지만, 안전하게 재확인하려면 유지 가능
- name: Ensure required packages present
  ansible.builtin.dnf:
    name:
      - podman
      - httpd-tools
    state: present

# 레지스트리 포트가 열릴 때까지 대기 (네트워크 안정화)
- name: Wait until registry ({{ registry_host }}:{{ registry_port }}) is reachable
  ansible.builtin.wait_for:
    host: "{{ registry_host }}"
    port: "{{ registry_port }}"
    timeout: 120
    state: started

# 필수: CA 파일 존재 확인 (DaemonSet이 반영되어 있어야 함)
- name: Check CA file on this node
  ansible.builtin.stat:
    path: "/etc/containers/certs.d/{{ registry_host }}:{{ registry_port }}/ca.crt"
  register: ca_stat

- name: Fail if CA file is missing
  ansible.builtin.fail:
    msg: "Missing CA: /etc/containers/certs.d/{{ registry_host }}:{{ registry_port }}/ca.crt"
  when: not ca_stat.stat.exists

# 원격 레지스트리에 로그인 (localhost 아님!)
- name: Podman login to {{ registry_host }}:{{ registry_port }}
  containers.podman.podman_login:
    registry: "{{ registry_host }}:{{ registry_port }}"
    username: "{{ registry_user }}"
    password: "{{ registry_password }}"
